trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Terraform..."
    wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    unzip terraform_1.5.7_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
  displayName: 'Install Terraform'

- script: |
    echo "Initializing Terraform..."
    terraform init
  displayName: 'Terraform Init'

- script: |
    echo "Applying Terraform configuration..."
    terraform apply -auto-approve
  displayName: 'Terraform Apply'